import Header from "@/components/Header";
import '../../public/styles/globals.css';
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import SearchBar from "@/components/SearchBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "./icon.ico",
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Providers>
          {/* header */}
          <Header />
          {/* navbar */}
          <Navbar />

          {/* search box */}
          <SearchBar />

          {children}  
       </Providers>
      </body>
    </html>
  )
}
